[package]
name = "vsock_to_tun_incoming"
version = "0.1.0"
edition = "2021"

[dependencies]
tun-tap = "0.1.4"
vsock = "0.1"
nix = "0.15"

[[bin]]
name = "vsock-to-tun-incoming"
path = "vsock_to_tun_incoming.rs"

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1